"""schema initial : dossiers, ecritures, lignes_ecriture

Revision ID: 4a6bdc777737
Revises: 
Create Date: 2026-09-05 14:49:14.303468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6bdc777737'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('forme_juridique', sa.String(), nullable=False),
    sa.Column('regime_imposition', sa.String(), nullable=False),
    sa.Column('regime_tva', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecritures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dossier_id', sa.String(), nullable=False),
    sa.Column('journal', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('libelle', sa.String(), nullable=False),
    sa.Column('reference_piece', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lignes_ecriture',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ecriture_id', sa.String(), nullable=False),
    sa.Column('compte', sa.String(), nullable=False),
    sa.Column('sens', sa.String(), nullable=False),
    sa.Column('montant_centimes', sa.BigInteger(), nullable=False),
    sa.Column('devise', sa.String(), nullable=False),
    sa.Column('analytique', sa.String(), nullable=True),
    sa.Column('code_tva', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ecriture_id'], ['ecritures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lignes_ecriture')
    op.drop_table('ecritures')
    op.drop_table('dossiers')
    # ### end Alembic commands ###
