"""decisions humaines et annotations dev

Revision ID: 55cf8c93e5bf
Revises: 4a6bdc777737
Create Date: 2026-09-07 21:48:17.086488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cf8c93e5bf'
down_revision: Union[str, Sequence[str], None] = '4a6bdc777737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations_dev',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dossier_id', sa.String(), nullable=False),
    sa.Column('ecriture_id', sa.String(), nullable=False),
    sa.Column('juste', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('annote_par', sa.String(), nullable=False),
    sa.Column('annote_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions_humaines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dossier_id', sa.String(), nullable=False),
    sa.Column('ecriture_id', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=False),
    sa.Column('etage_origine', sa.String(), nullable=False),
    sa.Column('confiance_origine', sa.Float(), nullable=False),
    sa.Column('decide_par', sa.String(), nullable=False),
    sa.Column('decide_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions_humaines')
    op.drop_table('annotations_dev')
    # ### end Alembic commands ###
