"""journal ingestion : archive brute, quarantaine, curseurs

Revision ID: a016d1659a6e
Revises: 614c1b3e65e8
Create Date: 2026-09-22 00:10:31.173802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a016d1659a6e'
down_revision: Union[str, Sequence[str], None] = '614c1b3e65e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curseurs_synchro',
    sa.Column('dossier_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('dernier_updated_at', sa.DateTime(), nullable=False),
    sa.Column('maj_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('dossier_id', 'source')
    )
    op.create_table('ingestion_brut',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dossier_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('recu_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_brut_dossier_id'), 'ingestion_brut', ['dossier_id'], unique=False)
    op.create_table('quarantaine_ingestion',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dossier_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('motif', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('mis_en_quarantaine_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarantaine_ingestion_dossier_id'), 'quarantaine_ingestion', ['dossier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quarantaine_ingestion_dossier_id'), table_name='quarantaine_ingestion')
    op.drop_table('quarantaine_ingestion')
    op.drop_index(op.f('ix_ingestion_brut_dossier_id'), table_name='ingestion_brut')
    op.drop_table('ingestion_brut')
    op.drop_table('curseurs_synchro')
    # ### end Alembic commands ###
